### ISSUE TITLE
More accurate logging during install

### ISSUE THREAD

**Issue by tomage** [jyveapp/django-pgtrigger#6]
I noticed that the library reports it's installing all current triggers every time migrations are run (or, more accurately, every time `pgtrigger.install()` is called).

Albeit not a big deal, it's not totally accurate, as most of the time, it's not actually installing them.

Digging thru the code, I can readily see why this is the case, but I also did some experimentation on how to change things to have pgtriggers report on these different actions:

* Installing trigger
* Pruning (deleting) trigger
* Updating trigger
* Updating trigger function

And I think it could be very helpful to get the logging to reflect what's happening behind the scenes. For example, if when running migrations against production system, the user would see install of some triggers that were not expected, that could raise some alarms. Or vice-versa, if the user was expecting to see a trigger be installed, or even a trigger function to be updated, it might be very useful to see it in the logs.

I tried to do some small changes to see if I could move logging closer to the actual SQL operations, and modify the code slightly to know when to report on which action.

If I understand the library correctly, we can split this "problem" into two: Named and unnamed triggers.

### Unnamed triggers

I believe that triggers, and their functions, if unnamed, are given names based on their definitions. This has some "good" properties w.r.t. the issue I'm reporting: Any change made to the definition of the trigger, or it's function, will result in a changed name. This means that if there's no change made to a trigger, nothing should get reported. If a change is made, we should end up reporting creation of a "new" trigger, and pruning/deletion of the original one.

The "only" change that might be needed here is to look to see if given unnamed trigger found in the code can be found in the DB. If not - we'll create it and log the creation.

### Named triggers

Here, things get more interesting, as changes to a trigger definition, or it's function, can be reflected as changes.

I started by looking into function definitions and came up with this approach:

* Remove the `OR REPLACE` from the trigger function create statement, making postgres raise an exception when the function exists.
* When the exception happens, use `pg_get_functiondef()` to get the current function definition from the database, and use the output to compare to the function as rendered from the code.
* If the function bodies differ, we then replace the function, and log that action accordingly. If they match, we don't log anything.

And I think a similar approach can be applied for the trigger itself.

I had implemented a (very) rough version of it.. But it's somewhat involved, and I wanted to get some feedback from @wesleykendall before either I commenced with a PR, or just let Wes try and implementation, as he is more familiar with the code.

It's also possible that the extra complexity of adjusting these logging messages may simply not be worth the extra complexity (there's also a (small) chance that this will slow the library down by the slightest, during the "installation" phase, tho since that is a rare event, that is probably fine).

**Comment by wesleykendall** [comment]
@tomage agreed that it would be nice behavior to have accurate logging, but I also think that this issue points out some other problems that users might face when wanting to know what's installed and what's going to change after a deployment

For unnamed triggers, I believe it hashes a lot of the properties of the triggers to determine a unique hash, but I wouldn't necessarily say that this always constitutes a unique trigger declaration. I would argue that we should get rid of unnamed triggers entirely since changing an unnamed trigger involves a drop/re-create that can have downtime problems during app migration. I was wary of doing this originally since it is a breaking API change, but I do think it would help consolidate some stuff down the road and make it easier for users to understand what's going to happen during migrations.

For the named ones, I would be interested to know if the declaration returned by postgres is an exact match to the declaration that is given during trigger creation. If so, this seems like a valid approach that we can use. Along with having more accurate logging of the installation process, we could use this strategy to also provide some management commands to users around which triggers are installed, and the "plan" for triggers during migrations.

If you are onboard with these particular changes, I'd say we split this up into the following:

1. Make everything be a named trigger and also check that names are unique so that there are no collisions. I believe pgtrigger currently doesn't do this. Currently named triggers look like this:

```
@pgtrigger.register(
    pgtrigger.Protect(name='protect_inserts', operation=pgtrigger.Insert)
)
```

I really wanted to do something like this originally though:

```
@pgtrigger.register(
    protect_inserts=pgtrigger.Protect(operation=pgtrigger.Insert)
)
```

This interface basically means we should avoid storing the "name" on the trigger object, which would involve a bit of re-work that I think would be worth it. And it would also mean we'd supply the "name" to the "install" method and all other "management" methods on triggers. This would still all fit in fine with the trigger registry pgtrigger uses for finding named triggers though. We'd need to make a breaking API change and add a bit more documentation for users that migrate (along with upgrading pghistory)

2. Update the internal management of our triggers so that we can accurately determine when a trigger is out of sync with the current declaration (i.e. use the approach outlined by you).

3. Now that everything is named and we have accurate ways of knowing what's going to be installed, we can make a few management commands for managing triggers. I'd propose the following:

    - `manage.py pgtrigger ls` - List all registered triggers and if they are installed, out of sync, or not installed (similar to manage.py show_migrations). The "out of sync" state basically means that the definition no longer matches the one returned by postgres.
    - `manage.py pgtrigger diff <trigger_name>` - Shows any changes that are present in the installed trigger and the trigger declared in code. We can figure out what type of output format makes sense
    - `manage.py pgtrigger enable|disable|install|uninstall` - For enabling/disabling/installing/uninstalling ALL triggers (if no trigger name is provided) or a set of triggers. Users are prompted by default when doing any destructive management command, and there is a "--dry-run" flag to see what will happen
    - `manage.py pgtrigger prune` - For pruning any triggers that were previously installed by pgtrigger that no longer exist in the codebase. This is an all or nothing operation and also has a "--dry-run" flag

These management commands are nice for people that maybe don't want an "install + prune" to always happen during migrations (i.e. disabling PGTRIGGER_INSTALL_ON_MIGRATE)

**Comment by wesleykendall** [comment]
It might be another week or so, but I'd be happy to tackle 1) as a first step to this. I think it might make 2) a lot easier to reason about/review.

**Comment by tomage** [comment]
Yeah - no rush on this per se. I just noticed there was a lot of output being printed for example when running unit-tests where DB would be created.

I wouldn't mind requiring names for the triggers. I imagine Django designers had to think about similar things for, for example, indexes, which can be named, but can also be left unnamed. Perhaps there's something from the index mechanics we can use for pgtriggers as well.

Tho - simply not allowing unnamed triggers will def. simplify the system.

There's also the case when a user renames a trigger - would there be a way for us to figure out that it was a rename, or should we just consider it to be a case of "trigger removed + trigger added".

But yeah, I def. like splitting this work into these two parts, and I like the ideas you lay out for the second part too - the added commands etc.

And I'd be fine if you wanted to tackle either/both of these - but feel totally free to pull me/others into any of the work, or at least reviews.

**Comment by wesleykendall** [comment]
@tomage wanted to give an update.

I started on this and the main complexity I've encountered is determining when triggers have changed and should be re-installed. Just showing when a trigger is installed/not installed is trivial. And it is pretty easy to enforce unique names in the software.

Although one can check the function definition for changes, the trigger condition, when, and event properties need to be checked for changes too. This is a pretty cumbersome problem to check in postgres. For example, if you make an ``UPDATE OF`` trigger, I still haven't found out how to query this in the postgres information schema. And even if I did, the ordering of how postgres stores this is likely to be different than how it's defined in code.

So, one thing I want to do before opening a PR is to solve the issue of knowing when a trigger has been updated. I believe we can use the ``COMMENT ON`` functionality in postgres for this very purpose. Every postgres object can have a free-form text comment placed on it, and I'm planning on having pgtrigger leave a comment of the full definition of the trigger. I.e. it will dump a serialized JSON of the entire trigger definition as a comment, which will give me a more accurate ability to check if the trigger has had any changes since last time it was installed in the DB.

Hope that makes sense. I wanted to make it so that it was as accurate as possible when someone listed all triggers and checked their installation status

**Comment by tomage** [comment]
Hey @wesleykendall. Yeah - funny - I had the same exact thought - if one could add some metadata (like comments) to the table definitions that could be used to see if the trigger, or it's function, has been changed.

Other than that, I also thought that perhaps it'd be a time to start logging triggers in a DB table - but if we could avoid it using PG comments--even better.

**Comment by tomage** [comment]
Closing this since https://github.com/jyveapp/django-pgtrigger/pull/11 fixes the problem.
