### ISSUE TITLE
Support for multiple DB connections

### ISSUE THREAD

**Issue by pbc** [jyveapp/django-pgtrigger#8]
From what I can see in the codebase, the `pgtrigger.core` module uses `from django.db import connection` to deliver the required DB connection, which means that it uses the `default` connection from `django.db.connections` and there is no way to change / override / configure that behaviour.

In my specific case, I need to support different groups of models which use different DBs and the default connection is not being used at all, which means that with a hardcoded default DB connection, I am unable to use this package on any of my projects.

In an ideal situation, I would like to be able to do the following:

```
from django.db import connections
import pgtrigger

@pgtrigger.register(
    pgtrigger.Trigger(
        level=pgtrigger.Statement,
        when=pgtrigger.After,
        operation=pgtrigger.Delete,
        referencing=pgtrigger.Referencing(old='old_values', new='new_values'),
        func=_some_trigger_function,
        db_connection=connections["some_connection"]
    )
)
class SomeModel(models.Model):
    pass
```

or 

```
from django.db import connections
import pgtrigger

@pgtrigger.register(
    db_connection=connections["some_connection"]
    pgtrigger.Trigger(
        level=pgtrigger.Statement,
        when=pgtrigger.After,
        operation=pgtrigger.Delete,
        referencing=pgtrigger.Referencing(old='old_values', new='new_values'),
        func=_some_trigger_function
    )
)
class SomeModel(models.Model):
    pass
```

which would allow me to specify the required connection via `db_connection` parameter.

Are there any plans to support multiple DB connections on a per trigger definition basis?

**Comment by wesleykendall** [comment]
@pbc apologies for the delay on this issue. I didn't expect for a multi-DB use case so soon!

One thing to clear up - Since database triggers are installed at the database level (similar to a schema change), it seems like this is a bug in how django-pgtrigger installs triggers.

By default, django-pgtrigger will install triggers for the models after migrations using the default connection. However, it seems like some of your models are installed on different databases. Correct me if I'm wrong, but you need to be able to install those triggers on the same database in which those models are migrated, right?

Can you elaborate on how you have set up your models so that they are properly installed across different databases? Do the models themselves already reference the database so that migrations are applied on the right database? Or do you do something special to install them across multiple databases?

I think there might be a different fix for this in django-pgtrigger, however, I do like your second approach if there isn't one. I.e. one can specific the database name so that the trigger is properly installed on that database during trigger installation.

**Comment by pbc** [comment]
no worries @wesleykendall , we're all busy.

> One thing to clear up - Since database triggers are installed at the database level (similar to a schema change), it seems like this is a bug in how django-pgtrigger installs triggers.

Yes, we could definitely classify it as a bug, because it doesn't take into account the fact that you might be running migrations on a different DB. However, this is a bit simplistic view of the problem, because I don't think django migrations allow you to hook into this part of the process (I might be wrong on this one).

> By default, django-pgtrigger will install triggers for the models after migrations using the default connection. However, it seems like some of your models are installed on different databases. Correct me if I'm wrong, but you need to be able to install those triggers on the same database in which those models are migrated, right?

Yes, that is correct.

> Can you elaborate on how you have set up your models so that they are properly installed across different databases? Do the models themselves already reference the database so that migrations are applied on the right database? Or do you do something special to install them across multiple databases?

The way it currently works is that we have a class called `DbRouter` which is being used as a DB router by plugging it into the django internals via the `DATABASE_ROUTERS` config option.

What this class does is it checks what is the value of the `model._meta.app_label` attribute on each model and based on this value it provides appropriate DB config name which should be used by the rest of the django modules.

This allows us to split models by django app in a single repository.

Here's the tweaked copy and paste of some of the code:

```python
DATABASE_ROUTERS = ["some_module.db_router.DbRouter"]

# this is a custom config setting used by the router to map app labels to appropriate DB configs
DATABASE_APPS_MAPPING = {
    "foo_app": "foo_app_db",
    "bar_app": "bar_app_db",
}

class DbRouter:
    """
    A router to control all model operations across different databases.

    If a given app label is not set in settings.DATABASE_APPS_MAPPING, the router
    will fallback to the `default` database.
    """

    def db_for_read(self, model, **hints):
        """Point all read operations to a specific database."""
        return settings.DATABASE_APPS_MAPPING.get(model._meta.app_label, None)

    def db_for_write(self, model, **hints):
        """Point all write operations to a specific database."""
        return settings.DATABASE_APPS_MAPPING.get(model._meta.app_label, None)

    def allow_migrate(self, db, app_label, model_name=None, **hints):
        if db in settings.DATABASE_APPS_MAPPING.values():
            return settings.DATABASE_APPS_MAPPING.get(app_label) == db
        elif app_label in settings.DATABASE_APPS_MAPPING:
            return False
        return None

class FooRecord(models.Model):

    something_here = models.CharField(max_length=200)

    class Meta:
        app_label = "foo_app"
        db_table = "some_table"

class BarRecord(models.Model):

    something_here = models.CharField(max_length=200)

    class Meta:
        app_label = "bar_app"
        db_table = "some_table"


```

**Comment by pbc** [comment]
If you see any other potential solutions to make the trigger installation work with the above setup, then I would love to hear your thoughts.

**Comment by arpitremarkable** [comment]
I faced the same issue so I quickly hacked a fix.
@pbc please test using https://github.com/jyveapp/django-pgtrigger/pull/15
If it works then maybe we can refactor the `global` hack used in my pull request to something more elegant.

**Comment by wesleykendall** [comment]
@pbc @arpitremarkable I commented on the PR. I think that @pbc 's initial suggestion of placing the database connection with the trigger registration will be the best bet for integrating this into django-pgtrigger properly. There are management commands and many other things that will need to know the database to which a model is persisted. It seems that providing the database in one place (the trigger registration) will work best.

I'm happy to implement this since it is going to be a bit involved with the management commands. I'm planning on going forward with the solution that looks like @pbc 's suggestion:

```
from django.db import connections
import pgtrigger

@pgtrigger.register(
    pgtrigger.Trigger(
        level=pgtrigger.Statement,
        when=pgtrigger.After,
        operation=pgtrigger.Delete,
        referencing=pgtrigger.Referencing(old='old_values', new='new_values'),
        func=_some_trigger_function
    ),
    database='some_connection'
)
class SomeModel(models.Model):
    pass
```

I.e. when you register triggers with a model that is installed on a non-default DB, you need to add the `database` keyword argument to the trigger registration.

This will ensure that `pgtrigger.igore`, `pgtrigger.install` and all other commands can work out of the box with no additional arguments.

Along with this, I will add an optional `--database` kwargs to all management commands. If provided, the management command will only work across triggers on a particular database. Otherwise the management commands will operate across all databases.

If you all have any more thoughts or feedback, let me know. I'm blocking off some time tomorrow to implement this if it seems like a good approach at a high level. And you all can review the PR and docs if you'd like.

**Comment by pbc** [comment]
@wesleykendall I think that what you're suggesting above would be ideal, so I would go ahead with it. Thanks.

**Comment by pbc** [comment]
@arpitremarkable Fair point. I forgot about these "pesky" routers ;) 

I think we have two separate concerns here:
- respecting the DATABASE_ROUTERS config when it comes to `allow_migrate`
- respecting the DATABASE_ROUTERS config when it comes to DB connections returned by `db_for_write`

If you have a more dynamic DB connection logic, then ideally you would use the DB connection returned by `db_for_write` and you wouldn't need hardcoded config param in the form of `database='some_connection'`.

As to respecting `allow_migrate` and routers in general, the question is, can you hook into this whole routing process at the stage that `pgtrigger` runs, because from what I recall it wasn't that easy due to how Django handles migrations.

On top of it, replicating the above handling when you run migrations on test DBs might be even more tricky because of how Django handles test DB configuration and connections in general.

**Comment by arpitremarkable** [comment]
There is no perfect solution since Django doesn't inherently support multi db setup.
So whatever we decide on here should be based more on practicality and usage rather than Zen of Django.
.
I guess what I am personally looking for is for the triggers to inherit same connection alias config as its respective model.

**Comment by wesleykendall** [comment]
@arpitremarkable @pbc  PR is at https://github.com/jyveapp/django-pgtrigger/pull/16

I looked into @arpitremarkable 's discussion around respecting `allow_migrate` and `db_for_write`. I eventually settled on only using `db_for_write` as the source of truth for determining which database should have a trigger installed.

The reasoning is primarily because of the complexity surrounding triggers being installed on multiple databases for the same model. `db_for_write` only allows one database to be specified per model.

I assume that it doesn't make sense to even install triggers on databases where the models aren't being written. Triggers are only applicable for update/insert/delete/truncate commands, so they are irrelevant on replicas and other things. Is my reasoning correct here?

In other words, if your model is configured for writing on the ``example`` database, the triggers for that model will now only be installed on the ``example`` database. All other trigger commands (ignore, enable, disable, etc) work the same.

I updated the `migrate` hook so that it only installs triggers for the database that was just migrated. This seems to fit with how django migrations work for multiple databases.

Not sure if you all use the management commands to see the installation status of triggers or to manually install/enable/etc, but the management commands work on all databases by default unless a ``--database`` argument is supplied. ``pgtrigger ls`` will also list the database of the trigger.

If for any reason you change the write DB for a trigger, it will be removed from the old database when the new one is installed.

**Comment by wesleykendall** [comment]
I still have quite a bit of documentation to update and tests to write, but let me know if you have any feedback. It will likely be a few more days before this can be reviewed by someone else and deployed

**Comment by pbc** [comment]
> I assume that it doesn't make sense to even install triggers on databases where the models aren't being written. Triggers are only applicable for update/insert/delete/truncate commands, so they are irrelevant on replicas and other things. Is my reasoning correct here?

I've run multiple related scenarios in my head before and they always circle back to the "write" DB so I would assume that this line of thought is correct.

**Comment by pbc** [comment]
> The reasoning is primarily because of the complexity surrounding triggers being installed on multiple databases for the same model. db_for_write only allows one database to be specified per model.

I would assume that if you're using some form of DB sharding / partitioning or a multi master setup, which would require installation of triggers on multiple DBs, then handling it via Django models might not be the best idea.

Therefore, I would focus on the "base" scenario to move the new feature forward and to gather any additional feedback later on.

**Comment by arpitremarkable** [comment]
LGTM mostly.

**Comment by tomage** [comment]
@pbc / @arpitremarkable: Closing the issue since https://github.com/jyveapp/django-pgtrigger/pull/16 adds the multi-DB support. There are some reasonable limitations (read in the PR, or in the updated docs). Feel free to re-open, or post a new issue if this doesn't fully solve the issue at hand.

Many thanks to @wesleykendall  for fielding this change - not particularly trivial, but very neatly implemented!

**Comment by tomage** [comment]
Just built and pushed to pypi, FYI: https://pypi.org/project/django-pgtrigger/2.2.0/

**Comment by arpitremarkable** [comment]
https://github.com/jyveapp/django-pgtrigger/pull/17
